import React from 'react';

import { Container } from '../../styles';

export default function Uxcontent() {
    return <Container>
        <div>
            <h1>Por que melhorar a experiência do usuário?</h1>
            <h2>Qual a Importância de Conhecer e Aplicar UX?</h2>
        </div>
        <span>O principal objetivo de melhorar a experiência do usuário é claro: Você quer ganhar mais dinheiro e para isso quer que as pessoas gostem do seu produto, pessoas que gostam do seu produto consequentemente se tornam uma divulgadora da sua marca e com isso mais e mais pessoas passam a usar. Hoje em dia a maioria das grandes empresas que vem crescendo, apostam grande parte da sua verba em times que trabalham diretamente em melhorar a experiência do usuário em seus produtos. Essas empresas sabem claramente o retorno de sucesso que um produto tem se a experiência do usuário é gratificante. Para concluir, entendemos que experiência do usuário é o que uma pessoa sente ao utilizar um produto. A experiência do usuário é essencial para deixar seu usuário feliz, um usuário feliz ama seu produto e se torna divulgador da sua marca.</span>
        <strong>Qual a Importância de Conhecer e Aplicar UX?</strong>
        <span>A foco do UX é colocar, em primeiro lugar, a perspectiva do usuário ao usar algum produto, serviço ou navegar por uma página da internet. Dessa forma, entender a jornada ou a experiência de usabilidade do usuário, visitante ou cliente é o que faz a diferença entre uma marca irrelevante e outra de sucesso. Um profissional ou empresa que se preocupa em estudar, analisar e entender a experiência do usuário, entregando um fluxo de consumo otimizado, tem bem mais chances de conquistar esse mesmo usuário. É nesse momento que as pessoas se sentem satisfeitas ou encantadas por alguma coisa, sendo incentivadas a continuar consumindo ou a experimentar algo pela primeira vez. Seja um serviço, produto, página na internet, dispositivo eletrônico ou objeto de satisfação pessoal, a importância do UX é fazer o usuário se sentir bem a todo momento na experiência de uso. E, com UX aplicado de forma eficiente, vem a vontade natural deste mesmo usuário a comprar mais de uma mesma marca, fazer renovações ou upgrades de produtos ou serviços escaláveis. Ele também pode querer compartilhar seu contentamento com conhecidos próximos. Além de também se sentir disposto a ajudar uma empresa a fazer melhorias em produtos ou serviços.</span>
        <strong>Vantagens do UX</strong>
        <span>De uma maneira geral, o objetivo principal do UX é encantar pessoas e deixá-las mais felizes na usabilidade de algum produto ou serviço. Essa satisfação vem junto com outras vantagens que o UX estudado e aplicado tem. Abaixo você confere 5 delas.</span>
        <span>1 - Aumentar Conversão nas Vendas: Um usuário que se sente satisfeito com a experiência de navegação de um site ou com os mecanismos de botões antes de efetivar a compra de um produto ou serviço tem bem mais chances de converter. Facilitar e deixar essas duas jornadas mais intuitivas é um grande diferencial para ter mais conversões. </span>
        <span>2 - Fidelizar Usuários e Clientes: A fidelização de usuários ou clientes acontece quando eles se sentem completamente à vontade com o sistema de navegação de um site ou inteiramente satisfeitos com a usabilidade de um produto ou serviço. E, uma vez fidelizados, é possível que não busquem informação em outros sites e nem novos produtos em outras marcas.</span>
        <span>3 - Economizar Recursos: Estudar, analisar e aplicar UX em páginas de internet ou na experiência de compra de serviços ou produtos economiza gastos com o replanejamento de todas as etapas desses processos. Junto a isso, também terá economia de tempo e de retrabalho dos profissionais envolvidos.  </span>
        <span>4 - Maior Valor Percebido Pelo Produto: O valor percebido por produto é a sensação que vem acompanhada com a aplicação eficaz do UX na experiência de usabilidade dele. Pode ser pela qualidade informação recebida de um site, pela quantidade de funcionalidades úteis de um aparelho eletrônico ou pelo custo-benefício de algo comprado.</span>
        <span>5 -Indicações e Recomendações: Usuário ou cliente feliz e satisfeito com a navegação de um site, processo de compra ou experiência de usabilidade de um produto se torna altamente inclinado a fazer recomendações de uma empresa. Esse mesmo usuário também pode se tornar um defensor de uma marca, fazendo indicações e ressaltando benefícios pela internet.  </span>
        <strong>Como UX (User Experience) se Relaciona com UI (User Interface)?</strong>
        <span>O UX (User Experience) é definido como a experiência geral do usuário ou consumidor na interação com algum site, produto ou serviço. São as emoções e sensações que ele tem ao mexer com algum material pelo espectro global do momento.   A UI (User Interface, ou Interface do Usuário) é entendida como algo que está inserido na UX. Mas a UI é bem mais focada em elementos que se organizam e compõem uma experiência específica recebida pelo usuário ou consumidor em uma página, produto ou serviço. Como exemplo, vamos considerar um smartphone. A UX aparece como a experiência de usabilidade geral, na forma como o usuário se sente em relação ao custo-benefício do produto ou se o produto satisfaz as necessidades básicas de uso do usuário. Isso inclui fazer ligações, recursos por aplicativos, sistema de fotos e assim por diante. Já a UI se volta para a experiência do usuário em elementos gráficos e visuais, mais internos e de interface do aparelho. É o tamanho e a qualidade de resolução da tela, a própria organização da interface de navegação, o posicionamento dos botões de volume e até mesmo a maneira como se instala a bateria. Assim, UX e UI se complementam. Em geral, os elementos dessas duas áreas, incluindo seus profissionais, trabalham em conjunto. Enquanto se pensa na interface que faz a ligação entre a interface e o usuário, ao mesmo tempo também se avalia na experiência final que esse mesmo usuário vai ter.</span>
    </Container>;
}
